<?php
/**
 * @version   $Id: gantry.config.php 9025 2013-04-02 09:23:04Z arifin $
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2013 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
defined('JPATH_BASE') or die();

$gantry_presets = array(
    'presets' => array(
        'preset1' => array(
            'name' => 'Preset 1',
            'contentstyle' => 'preset1',
            'header-background' => '#e0e6e6',
            'header-contrast' => 'dark',
            'header-pattern' => '0',
            'header-accent' => '#3cb2ce',
            'header-accent2' => '#fbf994',

            'showcase-background' => '#e5eaed',
            'showcase-accent' => '#3cb2ce',
            'showcase-accent2' => '#fbf994',
            'showcase-contrast' => 'light',
            'showcase-tinting' => '0',
            'showcase-pattern' => '0',
            'showcase-gradient' => 'none',

            'feature-background' => '#e5eaed',
            'feature-accent' => '#3cb2ce',
            'feature-accent2' => '#fbf994',
            'feature-contrast' => 'light',
            'feature-tinting' => '0',
            'feature-pattern' => 'none',
            'feature-gradient' => 'none',

            'utility-background' => '#198fab',
            'utility-accent' => '#3cb2ce',
            'utility-accent2' => '#fbf994',
            'utility-contrast' => 'dark',
            'utility-tinting' => '1',
            'utility-pattern' => '0',
            'utility-gradient' => 'gradient1',

            'main-body' => 'light',
            'main-accent' => '#3cb2ce',
            'main-accent2' => '#fbf994',
            'main-accentoverlay' => 'dark',

            'extension-background' => '#2c7d90',
            'extension-accent' => '#3cb2ce',
            'extension-accent2' => '#fbf994',
            'extension-contrast' => 'dark',
            'extension-tinting' => '0',
            'extension-pattern' => 'none',
            'extension-gradient' => 'none',

            'bottom-background' => '#e5eaed',
            'bottom-accent' => '#3cb2ce',
            'bottom-accent2' => '#fbf994',
            'bottom-contrast' => 'light',
            'bottom-tinting' => '0',
            'bottom-pattern' => 'noise',
            'bottom-gradient' => 'none',

            'footer-background' => '#0e80a4',
            'footer-accent' => '#3697b8',
            'footer-accent2' => '#fbf994',
            'footer-contrast' => 'dark',
            'footer-tinting' => '0',
            'footer-pattern' => 'noise',
            'footer-gradient' => 'none',
        ),

      'preset2' => array(
            'name' => 'Preset 2',
            'contentstyle' => 'preset2',
            'header-background' => '#8CB942',
            'header-contrast' => 'dark',
            'header-pattern' => '0',
            'header-accent' => '#8CB942',
            'header-accent2' => '#F7EDD2',

            'showcase-background' => '#e5eaed',
            'showcase-accent' => '#8CB942',
            'showcase-accent2' => '#F7EDD2',
            'showcase-contrast' => 'light',
            'showcase-tinting' => '0',
            'showcase-pattern' => '0',
            'showcase-gradient' => 'none',

            'feature-background' => '#e5eaed',
            'feature-accent' => '#8CB942',
            'feature-accent2' => '#F7EDD2',
            'feature-contrast' => 'light',
            'feature-tinting' => '0',
            'feature-pattern' => 'none',
            'feature-gradient' => 'none',

            'utility-background' => '#6E9B40',
            'utility-accent' => '#8CB942',
            'utility-accent2' => '#F7EDD2',
            'utility-contrast' => 'dark',
            'utility-tinting' => '1',
            'utility-pattern' => '0',
            'utility-gradient' => 'gradient1',

            'main-body' => 'light',
            'main-accent' => '#8CB942',
            'main-accent2' => '#F7EDD2',
            'main-accentoverlay' => 'dark',

            'extension-background' => '#6A8F46',
            'extension-accent' => '#8CB942',
            'extension-accent2' => '#F7EDD2',
            'extension-contrast' => 'dark',
            'extension-tinting' => '0',
            'extension-pattern' => 'none',
            'extension-gradient' => 'none',

            'bottom-background' => '#e5eaed',
            'bottom-accent' => '#8CB942',
            'bottom-accent2' => '#F7EDD2',
            'bottom-contrast' => 'light',
            'bottom-tinting' => '0',
            'bottom-pattern' => 'noise',
            'bottom-gradient' => 'none',

            'footer-background' => '#619244',
            'footer-accent' => '#8CB942',
            'footer-accent2' => '#F7EDD2',
            'footer-contrast' => 'dark',
            'footer-tinting' => '0',
            'footer-pattern' => 'noise',
            'footer-gradient' => 'none',
        ),

      'preset3' => array(
            'name' => 'Preset 3',
            'contentstyle' => 'preset3',
            'header-background' => '#FDF9F7',
            'header-contrast' => 'dark',
            'header-pattern' => '0',
            'header-accent' => '#E86435',
            'header-accent2' => '#BFEDF5',

            'showcase-background' => '#e5eaed',
            'showcase-accent' => '#E86435',
            'showcase-accent2' => '#BFEDF5',
            'showcase-contrast' => 'light',
            'showcase-tinting' => '0',
            'showcase-pattern' => '0',
            'showcase-gradient' => 'none',

            'feature-background' => '#e5eaed',
            'feature-accent' => '#E86435',
            'feature-accent2' => '#BFEDF5',
            'feature-contrast' => 'light',
            'feature-tinting' => '0',
            'feature-pattern' => 'none',
            'feature-gradient' => 'none',

            'utility-background' => '#C45438',
            'utility-accent' => '#E86435',
            'utility-accent2' => '#BFEDF5',
            'utility-contrast' => 'dark',
            'utility-tinting' => '1',
            'utility-pattern' => '0',
            'utility-gradient' => 'gradient1',

            'main-body' => 'light',
            'main-accent' => '#E86435',
            'main-accent2' => '#BFEDF5',
            'main-accentoverlay' => 'dark',

            'extension-background' => '#CC563A',
            'extension-accent' => '#E86435',
            'extension-accent2' => '#BFEDF5',
            'extension-contrast' => 'dark',
            'extension-tinting' => '0',
            'extension-pattern' => 'none',
            'extension-gradient' => 'none',

            'bottom-background' => '#e5eaed',
            'bottom-accent' => '#E86435',
            'bottom-accent2' => '#BFEDF5',
            'bottom-contrast' => 'light',
            'bottom-tinting' => '0',
            'bottom-pattern' => 'noise',
            'bottom-gradient' => 'none',

            'footer-background' => '#DE4F34',
            'footer-accent' => '#E86435',
            'footer-accent2' => '#BFEDF5',
            'footer-contrast' => 'dark',
            'footer-tinting' => '0',
            'footer-pattern' => 'noise',
            'footer-gradient' => 'none',
        ),

      'preset4' => array(
            'name' => 'Preset 4',
            'contentstyle' => 'preset4',
            'header-background' => '#8CB942',
            'header-contrast' => 'dark',
            'header-pattern' => '0',
            'header-accent' => '#CC2129',
            'header-accent2' => '#F5F2A1',

            'showcase-background' => '#e5eaed',
            'showcase-accent' => '#CC2129',
            'showcase-accent2' => '#F5F2A1',
            'showcase-contrast' => 'light',
            'showcase-tinting' => '0',
            'showcase-pattern' => '0',
            'showcase-gradient' => 'none',

            'feature-background' => '#e5eaed',
            'feature-accent' => '#CC2129',
            'feature-accent2' => '#F5F2A1',
            'feature-contrast' => 'light',
            'feature-tinting' => '0',
            'feature-pattern' => 'none',
            'feature-gradient' => 'none',

            'utility-background' => '#AE2026',
            'utility-accent' => '#CC2129',
            'utility-accent2' => '#F5F2A1',
            'utility-contrast' => 'dark',
            'utility-tinting' => '1',
            'utility-pattern' => '0',
            'utility-gradient' => 'gradient1',

            'main-body' => 'light',
            'main-accent' => '#CC2129',
            'main-accent2' => '#F5F2A1',
            'main-accentoverlay' => 'dark',

            'extension-background' => '#B2343A',
            'extension-accent' => '#CC2129',
            'extension-accent2' => '#E5B466',
            'extension-contrast' => 'dark',
            'extension-tinting' => '0',
            'extension-pattern' => 'none',
            'extension-gradient' => 'none',

            'bottom-background' => '#e5eaed',
            'bottom-accent' => '#CC2129',
            'bottom-accent2' => '#F5F2A1',
            'bottom-contrast' => 'light',
            'bottom-tinting' => '0',
            'bottom-pattern' => 'noise',
            'bottom-gradient' => 'none',

            'footer-background' => '#BC2429',
            'footer-accent' => '#CC2129',
            'footer-accent2' => '#F5F2A1',
            'footer-contrast' => 'dark',
            'footer-tinting' => '0',
            'footer-pattern' => 'noise',
            'footer-gradient' => 'none',
        ),

		'preset5' => array(
            'name' => 'Preset 5',
            'contentstyle' => 'preset5',
            'header-background' => '#8CB942',
            'header-contrast' => 'dark',
            'header-pattern' => '0',
            'header-accent' => '#497CCA',
            'header-accent2' => '#F7C1A5',

            'showcase-background' => '#e5eaed',
            'showcase-accent' => '#497CCA',
            'showcase-accent2' => '#F7C1A5',
            'showcase-contrast' => 'light',
            'showcase-tinting' => '0',
            'showcase-pattern' => '0',
            'showcase-gradient' => 'none',

            'feature-background' => '#e5eaed',
            'feature-accent' => '#497CCA',
            'feature-accent2' => '#F7C1A5',
            'feature-contrast' => 'light',
            'feature-tinting' => '0',
            'feature-pattern' => 'none',
            'feature-gradient' => 'none',

            'utility-background' => '#3F65B1',
            'utility-accent' => '#497CCA',
            'utility-accent2' => '#F7C1A5',
            'utility-contrast' => 'dark',
            'utility-tinting' => '1',
            'utility-pattern' => '0',
            'utility-gradient' => 'gradient1',

            'main-body' => 'light',
            'main-accent' => '#497CCA',
            'main-accent2' => '#F7C1A5',
            'main-accentoverlay' => 'dark',

            'extension-background' => '#4468A8',
            'extension-accent' => '#497CCA',
            'extension-accent2' => '#F7C1A5',
            'extension-contrast' => 'dark',
            'extension-tinting' => '0',
            'extension-pattern' => 'none',
            'extension-gradient' => 'none',

            'bottom-background' => '#e5eaed',
            'bottom-accent' => '#497CCA',
            'bottom-accent2' => '#F7C1A5',
            'bottom-contrast' => 'light',
            'bottom-tinting' => '0',
            'bottom-pattern' => 'noise',
            'bottom-gradient' => 'none',

            'footer-background' => '#334A96',
            'footer-accent' => '#497CCA',
            'footer-accent2' => '#F7C1A5',
            'footer-contrast' => 'dark',
            'footer-tinting' => '0',
            'footer-pattern' => 'noise',
            'footer-gradient' => 'none',
        ),

      'preset6' => array(
            'name' => 'Preset 6',
            'contentstyle' => 'preset6',
            'header-background' => '#574D4F',
            'header-contrast' => 'dark',
            'header-pattern' => '0',
            'header-accent' => '#746F73',
            'header-accent2' => '#F5F3A4',

            'showcase-background' => '#e5eaed',
            'showcase-accent' => '#746F73',
            'showcase-accent2' => '#F5F3A4',
            'showcase-contrast' => 'light',
            'showcase-tinting' => '0',
            'showcase-pattern' => '0',
            'showcase-gradient' => 'none',

            'feature-background' => '#e5eaed',
            'feature-accent' => '#746F73',
            'feature-accent2' => '#F5F3A4',
            'feature-contrast' => 'light',
            'feature-tinting' => '0',
            'feature-pattern' => 'none',
            'feature-gradient' => 'none',

            'utility-background' => '#37343B',
            'utility-accent' => '#746F73',
            'utility-accent2' => '#F5F3A4',
            'utility-contrast' => 'dark',
            'utility-tinting' => '1',
            'utility-pattern' => '0',
            'utility-gradient' => 'gradient1',

            'main-body' => 'light',
            'main-accent' => '#746F73',
            'main-accent2' => '#F5F3A4',
            'main-accentoverlay' => 'dark',

            'extension-background' => '#6B646D',
            'extension-accent' => '#746F73',
            'extension-accent2' => '#F5F3A4',
            'extension-contrast' => 'dark',
            'extension-tinting' => '0',
            'extension-pattern' => 'none',
            'extension-gradient' => 'none',

            'bottom-background' => '#e5eaed',
            'bottom-accent' => '#746F73',
            'bottom-accent2' => '#F5F3A4',
            'bottom-contrast' => 'light',
            'bottom-tinting' => '0',
            'bottom-pattern' => 'noise',
            'bottom-gradient' => 'none',

            'footer-background' => '#5B575F',
            'footer-accent' => '#746F73',
            'footer-accent2' => '#F5F3A4',
            'footer-contrast' => 'dark',
            'footer-tinting' => '0',
            'footer-pattern' => 'noise',
            'footer-gradient' => 'none',
        )
    )
);
